### ISSUE TITLE
dataset problem

### ISSUE THREAD

**Issue by LingJiangXie** [clcarwin/sphereface_pytorch#11]
Hi ! Thank you for this pytorch version sphereface code ,I have found this for a long time .But when I run train.py ,some problems occured. 
  VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future  nparrimage = np.frombuffer(arrimage.get_obj(),np.float32).reshape(10,len(arrimage)/10) .I think my numpy version(1.11.0) is not fine. 
  'There is no item named %r in the archive' % name) KeyError: "There is no item named '1212722/038.jpg' in the archive" . But I find this image in the fold 1212722 .
  Last problem may I get the mtcnn landmarks for casia? or you can tell me mtcnn codes ,I run it.Thank you very much!

**Comment by LingJiangXie** [comment]
When I changed my python from 3.6 to 2.7 .Problem "VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future nparrimage = np.frombuffer(arrimage.get_obj(),np.float32).reshape(10,len(arrimage)/10) ." disappeared. And I find the landmarks in the fold (data).But problem some image not found still exists.I thinlk multiprocessing module to read images cause the problem.Can you tell me how to fix it ?

**Comment by LingJiangXie** [comment]
Process Process-1:
Traceback (most recent call last):
  File "/home/dany/anaconda3/envs/snakes/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/dany/anaconda3/envs/snakes/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dany/Documents/workspace/sphereface_pytorch-master_2.7/dataset.py", line 38, in dataset_handle
    data = callback(name,filename,pindex,cacheobj,zfile)
  File "/home/dany/Documents/workspace/sphereface_pytorch-master_2.7/train.py", line 54, in dataset_load
    data = np.frombuffer(zfile.read(nameinzip),np.uint8)
  File "/home/dany/anaconda3/envs/snakes/lib/python2.7/zipfile.py", line 938, in read
    return self.open(name, "r", pwd).read()
  File "/home/dany/anaconda3/envs/snakes/lib/python2.7/zipfile.py", line 964, in open
    zinfo = self.getinfo(name)
  File "/home/dany/anaconda3/envs/snakes/lib/python2.7/zipfile.py", line 912, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named '3331486/011.jpg' in the archive"
Process Process-2:
Traceback (most recent call last):
  File "/home/dany/anaconda3/envs/snakes/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/dany/anaconda3/envs/snakes/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dany/Documents/workspace/sphereface_pytorch-master_2.7/dataset.py", line 38, in dataset_handle
    data = callback(name,filename,pindex,cacheobj,zfile)
  File "/home/dany/Documents/workspace/sphereface_pytorch-master_2.7/train.py", line 54, in dataset_load
    data = np.frombuffer(zfile.read(nameinzip),np.uint8)
  File "/home/dany/anaconda3/envs/snakes/lib/python2.7/zipfile.py", line 938, in read
    return self.open(name, "r", pwd).read()
  File "/home/dany/anaconda3/envs/snakes/lib/python2.7/zipfile.py", line 964, in open
    zinfo = self.getinfo(name)
  File "/home/dany/anaconda3/envs/snakes/lib/python2.7/zipfile.py", line 912, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named '0235966/005.jpg' in the archive"

**Comment by lucaskyle** [comment]
same problem here:

Traceback (most recent call last):
  File "lfw_eval.py", line 102, in <module>
    img1 = alignment(cv2.imdecode(np.frombuffer(zfile.read(name1),np.uint8),1),landmark[name1])
  File "/home/learning-pc/anaconda3/lib/python3.6/zipfile.py", line 1314, in read
    with self.open(name, "r", pwd) as fp:
  File "/home/learning-pc/anaconda3/lib/python3.6/zipfile.py", line 1352, in open
    zinfo = self.getinfo(name)
  File "/home/learning-pc/anaconda3/lib/python3.6/zipfile.py", line 1281, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named '/home/learning-pc/Documents/data/lfw/lfw/Abel_Pacheco/Abel_Pacheco_0001.jpg' in the archive"

trying to run eval_LFW...

**Comment by lucaskyle** [comment]
plz check the path should be   /..../.../lfw.zip/file_name/xxx.jpg

**Comment by LingJiangXie** [comment]
Yes,I have checked ...

**Comment by hujuan940506** [comment]
I have the same problem as LingJiangXie, I want to ask you that your problem has been solved？

Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/liuyh/IDcar/sphereface_pytorch-master/dataset.py", line 38, in dataset_handle
    data = callback(name,filename,pindex,cacheobj,zfile)
  File "train.py", line 59, in dataset_load
    print(zfile.read('casia/' + nameinzip))
  File "/usr/lib/python2.7/zipfile.py", line 935, in read
    return self.open(name, "r", pwd).read()
  File "/usr/lib/python2.7/zipfile.py", line 961, in open
    zinfo = self.getinfo(name)
  File "/usr/lib/python2.7/zipfile.py", line 909, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'casia/0001392/091.jpg' in the archive"

**Comment by LingJiangXie** [comment]
Not solved.......

**Comment by clcarwin** [comment]
Please try to read this issue #3 .

**Comment by LingJiangXie** [comment]
Thank you !

**Comment by hujuan940506** [comment]
@clcarwin  Thank you very much!

**Comment by hujuan940506** [comment]
Have you solved it now? @LingJiangXie

**Comment by LingJiangXie** [comment]
Downloading datasets 
https://pan.baidu.com/s/1i5gX7Dz
d31k

**Comment by dpcross** [comment]
modify this line  zfile.read('nameinzip) to zfile.read('CASIA-WebFace/'+nameinzip) (train.py)

**Comment by dpcross** [comment]
modify this line zfile.read('nameinzip) to zfile.read('CASIA-WebFace/'+nameinzip) (train.py)

**Comment by dpcross** [comment]
modify  zfile.read('nameinzip) to zfile.read('CASIA-WebFace/'+nameinzip) (train.py)
add try catch before data = callback(name,filename,pindex,cacheobj,zfile)  ,continue except

**Comment by hujuan940506** [comment]
@dpcross Thank you very much! I have solved this route problem in your way, but I have encountered this problem:

Traceback (most recent call last):
  File "train.py", line 162, in <module>
    train(epoch,args)
  File "train.py", line 131, in train
    outputs = net(inputs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/liuyh/IDcar/sphereface_pytorch-master/net_sphere.py", line 175, in forward
    x = self.fc6(x)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/liuyh/IDcar/sphereface_pytorch-master/net_sphere.py", line 40, in forward
    cos_theta = cos_theta / xlen.view(-1,1) / wlen.view(1,-1)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/variable.py", line 780, in __div__
    return self.div(other)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/variable.py", line 312, in div
    return Div()(self, other)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/_functions/basic_ops.py", line 57, in forward
    return a.div(b)
RuntimeError: sizes do not match at /b/wheel/pytorch-src/torch/lib/THC/generated/../generic/THCTensorMathPointwise.cu:344

**Comment by hujuan940506** [comment]
@LingJiangXie Have you encounter this problem in your trainning process

**Comment by hujuan940506** [comment]
@clcarwin Thank you very much! I have solved this problem in your way, update pytorch to version 0.2.x.

**Comment by sevenHsu** [comment]
I just have the same problem with you guys.And my pytorch version is 0.2.0_3,but it does'nt work.How can i solve this problem??
_Traceback (most recent call last):
  File "lfw_eval.py", line 102, in <module>
    img1 = alignment(cv2.imdecode(np.frombuffer(zfile.read(name1),np.uint8),1),landmark[name1])
  File "/usr/lib/python3.6/zipfile.py", line 1314, in read
    with self.open(name, "r", pwd) as fp:
  File "/usr/lib/python3.6/zipfile.py", line 1352, in open
    zinfo = self.getinfo(name)
  File "/usr/lib/python3.6/zipfile.py", line 1281, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'Abel_Pacheco/Abel_Pacheco_0001.jpg' in the archive"_

**Comment by lucaskyle** [comment]
just need good washed  CASIA.zip dataset.


________________________________
发件人: Seven.Hsu <notifications@github.com>
发送时间: 2018年4月1日 12:46
收件人: clcarwin/sphereface_pytorch
抄送: lucaskyle; Comment
主题: Re: [clcarwin/sphereface_pytorch] dataset problem (#11)


I just have the same problem with you guys.And my pytorch version is 0.2.0_3,but it does'nt work.How can i solve this problem??
Traceback (most recent call last):
File "lfw_eval.py", line 102, in
img1 = alignment(cv2.imdecode(np.frombuffer(zfile.read(name1),np.uint8),1),landmark[name1])
File "/usr/lib/python3.6/zipfile.py", line 1314, in read
with self.open(name, "r", pwd) as fp:
File "/usr/lib/python3.6/zipfile.py", line 1352, in open
zinfo = self.getinfo(name)
File "/usr/lib/python3.6/zipfile.py", line 1281, in getinfo
'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'Abel_Pacheco/Abel_Pacheco_0001.jpg' in the archive"

―

**Comment by sevenHsu** [comment]
Thank you so much.I'll try it in your way.

**Comment by sevenHsu** [comment]
@LingJiangXie There are six .zip files in your BaiduPan.Which one should I download for my model trainning?or all of them?

**Comment by yonger001** [comment]
hi，guys. when I run the train.py,I got a problem as fllows.
        KeyError: "There is no item named '1478996/020.jpg' in the archive"
then i modified the np.frombuffer(zfile.read(nameinzip),np.uint8) to np.frombuffer(zfile.read(a+nameinzip),np.uint8), a+nameinzip is the absolute path of image,but it didn‘t work. 
Do you have any idea? 
thank you so much!waiting for your reply！

**Comment by netpcvnn** [comment]
Hi @LingJiangXie, Can you upload the washed dataset to other sites? I cannot to download from baidu because we dont have Chinese mobile phone number to activate the account.
Thank you!

**Comment by chenmingjiong** [comment]
> Hi @LingJiangXie, Can you upload the washed dataset to other sites? I cannot to download from baidu because we dont have Chinese mobile phone number to activate the account.
> Thank you!

I have uploaded it to OneDrive:
[https://1drv.ms/u/s!AjMP8wpvXdkfhMhnmNDEdj5oor7M_A](https://1drv.ms/u/s!AjMP8wpvXdkfhMhnmNDEdj5oor7M_A)

**Comment by helang818** [comment]
> hi，guys. when I run the train.py,I got a problem as fllows. KeyError: "There is no item named '1478996/020.jpg' in the archive" then i modified the np.frombuffer(zfile.read(nameinzip),np.uint8) to np.frombuffer(zfile.read(a+nameinzip),np.uint8), a+nameinzip is the absolute path of image,but it didn‘t work. Do you have any idea? thank you so much!waiting for your reply！

have you soved this issue?
