### ISSUE TITLE
unicode error

### ISSUE THREAD

**Issue by sevenHsu** [clcarwin/sphereface_pytorch#25]
Thanks for your contribution firstly.
I ran train.py on win10 based on pytorch0.3.
Traceback (most recent call last):
#     **File "train.py", line 15, in <module>
    from matlab_cp2tform import get_similarity_transform_for_cv2
    File "D:\Program Files\git_repository\sphereface_pytorch\matlab_cp2tform.py", line 167
    """
    SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 1266-1267: truncated  \UXXXXXXXX escape**
How to solve this issue?Thank you.

**Comment by 131Prince** [comment]
有解决办法吗

**Comment by duanzhibin** [comment]
I meet the same problem, have you solved it? Thanks, if you can share a solution for working around.

**Comment by sevenHsu** [comment]
@131Prince  Yes,I have solved this problem.I just update my Pytorch to V2.0 before this issue been solved.Maybe you need to check the version of your Pytorch .

**Comment by duanzhibin** [comment]
@sevenHsu Thank you at first.But my Pytorch version is 0.3.2,it is the latest vision.

**Comment by amjltc295** [comment]
@131Prince I removed all comments starting with '%' (all Matlab codes) and solved the problem.

**Comment by hvthaibk** [comment]
Replacing 'X\U' by 'X \ U' solved the problem for me.
