### ISSUE TITLE
read data errors

### ISSUE THREAD

**Issue by zhao181** [clcarwin/sphereface_pytorch#35]
Dear author, 
The following errors occurs when I run the train.py for training.
Would your please help me solve the problems?
I am looking forward to your reply. Thanks very much.

Process Process-1:
Process Process-6:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/ygzhao/ProGram1/Anaconda3x501/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ygzhao/ProGram1/Anaconda3x501/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ygzhao/ProGram1/Anaconda3x501/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ygzhao/ProDataS/FaceProc/sphereface/dataset.py", line 38, in dataset_handle
    data = callback(name,filename,pindex,cacheobj,zfile)
  File "/home/ygzhao/ProDataS/FaceProc/sphereface/train.py", line 56, in dataset_load
    data = np.frombuffer(zfile.read(nameinzip),np.uint8)
  File "/home/ygzhao/ProGram1/Anaconda3x501/lib/python3.6/zipfile.py", line 1315, in read
    return fp.read()
  File "/home/ygzhao/ProGram1/Anaconda3x501/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ygzhao/ProDataS/FaceProc/sphereface/dataset.py", line 38, in dataset_handle
    data = callback(name,filename,pindex,cacheobj,zfile)
  File "/home/ygzhao/ProGram1/Anaconda3x501/lib/python3.6/zipfile.py", line 835, in read
    buf += self._read1(self.MAX_N)
  File "/home/ygzhao/ProGram1/Anaconda3x501/lib/python3.6/zipfile.py", line 939, in _read1
    self._update_crc(data)
  File "/home/ygzhao/ProDataS/FaceProc/sphereface/train.py", line 56, in dataset_load
    data = np.frombuffer(zfile.read(nameinzip),np.uint8)
  File "/home/ygzhao/ProGram1/Anaconda3x501/lib/python3.6/zipfile.py", line 1315, in read
    return fp.read()

**Comment by chaochao12345lala** [comment]
did you question solved ?
