### ISSUE TITLE
CUDA error: out of memory

### ISSUE THREAD

**Issue by YogaLYJ** [clcarwin/sphereface_pytorch#46]
Thank u for ur nice work! I run train.py under python2.7 pytorch0.4.1, 12G GPU, but get the following error:

Traceback (most recent call last):
  File "/home/.../PycharmProjects/sphereface_pytorch-master/train.py", line 134, in <module>
    net.cuda()
  File "/home/.../anaconda3/envs/python2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 258, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/.../anaconda3/envs/python2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/home/.../anaconda3/envs/python2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 191, in _apply
    param.data = fn(param.data)
  File "/home/.../anaconda3/envs/python2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 258, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory

How could I run it successfuly?

**Comment by Pengyang233** [comment]
net.cuda(device = x), x is your gpu number you want to use

**Comment by chaochao12345lala** [comment]
内存不够导致的

**Comment by SherrySwift** [comment]
I met the same problem, how did you solve it?
